src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\ManyToMany(targetEntity: Domains::class, inversedBy: 'users', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $domains;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_name = null;

    #[ORM\Column(length: 2)]
    private ?string $language = 'null';

    public function __construct()
    {
        $this->domains = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Domains>
     */
    public function getDomains(): Collection
    {
        return $this->domains;
    }

    public function addDomain(Domains $domain): static
    {
        if (!$this->domains->contains($domain)) {
            $this->domains->add($domain);
        }

        return $this;
    }

    public function removeDomain(Domains $domain): static
    {
        $this->domains->removeElement($domain);

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): static
    {
        $this->language = $language;

        return $this;
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

use App\Form\UserFormType;
use App\Form\UserProfileFormType;
use App\Form\DeleteFormType;

use App\Entity\Users;

use App\Repository\UsersRepository;

class UsersController extends AbstractController
{
    private $em;
    private $router;
    private $translator;

    public function __construct(EntityManagerInterface $em, UrlGeneratorInterface $router, TranslatorInterface $translator)
    {
        $this->em = $em;
        $this->router = $router;
        $this->translator = $translator;
    }

    #[Route('/users', name: 'app_users')]
    public function index(): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if (!$this->getUser() || !$this->isGranted('IS_AUTHENTICATED')) {
            return $this->redirectToRoute('app_login');
        }

        $pages = array("page" => 1,"next" => false,"prev" => false);

        if(isset($_GET["page"]) && $_GET["page"] > 0) {
            $pages["page"] = intval($_GET["page"]);
        } else {
            $pages["page"] = 1;
        }

        if(isset($_GET["perpage"]) && $_GET["perpage"] > 0) {
            $pages["perpage"] = intval($_GET["perpage"]);
        } else {
            $pages["perpage"] = 10;
        }

        $repository = $this->em->getRepository(Users::class);
        $users = $repository->findBy(array(), array('id' => 'DESC'), $pages["perpage"], ($pages["page"] - 1) * $pages["perpage"]);
        $pages["totalitems"] = $repository->getTotalRows();
        $pages["start"] = $pages["totalitems"] - (($pages["page"] - 1) * $pages["perpage"]); 
        $pages["end"] = $pages["totalitems"] - (($pages["page"] - 1) * $pages["perpage"]) - $pages['perpage'] + 1;
        if ($pages["end"] < 0) {
            $pages["end"] = 1;
        }

        if(count($users) == 0 && $pages["totalitems"] != 0) {
            return $this->redirectToRoute('app_logs');
        }

        $pages["total"] = ceil($pages["totalitems"] / $pages['perpage']);
        if($pages["totalitems"] / $pages["perpage"] > $pages["page"]) {
            $pages["next"] = true;
        }
        if($pages["page"] - 1 > 0) {
            $pages["prev"] = true;
        }

        return $this->render('users/index.html.twig', [
            'users' => $users,
            'pages' => $pages,
            'page' => array(
                'menu' => array(
                    'category' => 'settings',
                    'item' => 'users'
                ),
                'pretitle' => $this->translator->trans("Settings"),
                'title' => $this->translator->trans("Users"),
                'actions' => array(
                    0 => array(
                        'primary' => true,
                        'name' => $this->translator->trans("Add"),
                        'target' => $this->router->generate('app_users_add'),
                        'icon' => "plus"
                    ),
                ),
            ),
            'breadcrumbs' => array(array('name' => $this->translator->trans("Users"), 'url' => $this->router->generate('app_users'))),
        ]);
    }

    #[Route('/users/add', name: 'app_users_add')]
    public function add(Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        if (!$this->getUser() || !$this->isGranted('IS_AUTHENTICATED')) {
            return $this->redirectToRoute('app_login');
        }

        $form = $this->createForm(UserFormType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formdata = $form->getData();

            $password1 = $form->get("password1")->getData();
            $password2 = $form->get("password2")->getData();

            if($password1 == $password2 && $password1 != "") {
                $formdata->setPassword(
                    $userPasswordHasher->hashPassword(
                        $formdata,
                        $form->get('password1')->getData()
                    )
                );
            } else {
                $this->addFlash('danger', $this->translator->trans("Passwords do not match"));
                return $this->redirectToRoute('app_users_add');
            }

            $is_admin = $form->get("isAdmin")->getData();

            $domain_roles = $form->get("roles")->getData();
            $roles = array();
            foreach($domain_roles as $domain) {
                $formdata->addDomain($domain);
            }
            if($is_admin == true) {
                array_push($roles, "ROLE_ADMIN");
            }
            $formdata->setRoles($roles);

            $this->em->persist($formdata);
            $this->em->flush();

            return $this->redirectToRoute('app_users');
        }
        $setup['users_form'] = $form->createView();

        return $this->render('users/edit.html.twig', [
            'page' => array(
                'menu' => array(
                    'category' => 'settings',
                    'item' => 'users'
                ),
                'pretitle' => $this->translator->trans("Settings"),
                'title' => $this->translator->trans("Add user"),
                'actions' => array(),
            ),
            'user' => null,
            'form' => $form,
            'breadcrumbs' => array(
                array('name' => $this->translator->trans("Users"), 'url' => $this->router->generate('app_users')),
                array('name' => $this->translator->trans("Add new user"), 'url' => $this->router->generate('app_users'))
            ),
        ]);
    }

    #[Route('/users/edit/{user}', name: 'app_users_edit')]
    public function edit(Users $user, Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        if (!$this->getUser() || !$this->isGranted('IS_AUTHENTICATED')) {
            return $this->redirectToRoute('app_login');
        }

        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(UserFormType::class, $user);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formdata = $form->getData();

            $password1 = $form->get("password1")->getData();
            $password2 = $form->get("password2")->getData();

            if(!is_null($password1)) {
                if($password1 == $password2) {
                    $formdata->setPassword(
                        $userPasswordHasher->hashPassword(
                            $formdata,
                            $form->get('password1')->getData()
                        )
                    );
                    $this->addFlash('success', $this->translator->trans("Password updated"));
                } else {
                    $this->addFlash('danger', $this->translator->trans("Passwords do not match"));
                    return $this->redirectToRoute('app_users_edit', ['user' => $user->getId()]);
                }
            }

            $is_admin = $form->get("isAdmin")->getData();

            $domain_roles = $form->get("roles")->getData();
            $roles = array();
            foreach($domain_roles as $domain) {
                $formdata->addDomain($domain);
            }
            if($is_admin == true) {
                array_push($roles, "ROLE_ADMIN");
            }
            $formdata->setRoles($roles);

            $this->em->persist($formdata);
            $this->em->flush();

            return $this->redirectToRoute('app_users');
        }

        return $this->render('users/edit.html.twig', [
            'page' => array(
                'menu' => array(
                    'category' => 'settings',
                    'item' => 'users'
                ),
                'pretitle' => $this->translator->trans("Settings"),
                'title' => $this->translator->trans("Edit user ".$user->getEmail()),
                'actions' => array(),
            ),
            'user' => $user,
            'form' => $form,
            'breadcrumbs' => array(
                array('name' => $this->translator->trans("Users"), 'url' => $this->router->generate('app_users')),
                array('name' => $user->getEmail(), 'url' => $this->router->generate('app_users'))
            ),
        ]);
    }

    #[Route('/user/profile', name: 'app_user_profile')]
    public function edit_profile(Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        if (!$this->getUser() || !$this->isGranted('IS_AUTHENTICATED')) {
            return $this->redirectToRoute('app_login');
        }

        $form = $this->createForm(UserProfileFormType::class, $this->getUser());

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formdata = $form->getData();
            
            if(!empty($form->get("password0")->getData())) {
                $formdata->setPassword($this->getUser()->getPassword());

                if($userPasswordHasher->isPasswordValid($this->getUser(), $form->get("password0")->getData())) {
                    if($form->get("password1")->getData() == $form->get("password2")->getData()){
                        $formdata->setPassword(
                            $userPasswordHasher->hashPassword(
                                $formdata,
                                $form->get('password1')->getData()
                            )
                        );

templates/users/edit.html.twig
{% extends 'base/page.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block body %}
                {{ form_start(form) }}
                <div class="row my-4">
					<div class="col-12 col-md-6 col-lg-6 mb-4 mb-lg-0">
						<div class="card mb-3">
							<h5 class="card-header">{{ "Name"|trans }}</h5>
							<div class="card-body">
								<p class="card-text">
									{{ form_row(form.first_name) }}
									{{ form_row(form.last_name) }}
								</p>
							</div>
						</div>
						<div class="card mb-3">
							<h5 class="card-header">{{ "Email address"|trans }}</h5>
							<div class="card-body">
								<p class="card-text">
									{{ form_row(form.email) }}
									{{ form_row(form.isVerified) }}
								</p>
							</div>
						</div>
						<div class="card mb-3">
							<h5 class="card-header">{{ "Change Password"|trans }}</h5>
							<div class="card-body">
								<p class="card-text">
									{{ form_row(form.password1) }}
									{{ form_row(form.password2) }}
								</p>
							</div>
						</div>
					</div>
					<div class="col-12 col-md-6 col-lg-6 mb-4 mb-lg-0">
						<div class="card mb-3">
							<h5 class="card-header">{{ "Allowed domains"|trans }}</h5>
							<div class="card-body">
								<p class="card-text">
									{{ form_row(form.roles) }}
								</p>
							</div>
						</div>
						<div class="card mb-3">
							<h5 class="card-header">{{ "Admin role"|trans }}</h5>
							<div class="card-body">
								<p class="card-text">
									{{ form_row(form.isAdmin) }}
								</p>
							</div>
						</div>
					</div>
				</div>
				<p></p>
				<button class="btn btn-success" type="submit">{% if user != null %}{{ 'Edit user'|trans }}{% else %}{{ 'Add user'|trans }}{% endif %}</button>
				{{ form_end(form) }}
{% endblock %}

templates/users/edit_profile.html.twig
{% extends 'base/page.html.twig' %}

{% block stylesheets %}{% endblock %}

{% block body %}
								{{ form_start(form) }}
								<div class="row my-4">
									<div class="col-12 col-md-6 col-lg-6 mb-4 mb-lg-0">
										<div class="card">
											<h5 class="card-header">{{ "Name"|trans }}</h5>
											<div class="card-body">
												<p class="card-text">
													{{ form_row(form.first_name) }}
													{{ form_row(form.last_name) }}
												</p>
											</div>
										</div>
									</div>
									<div class="col-12 col-md-6 col-lg-6 mb-4 mb-lg-0">
										<div class="card mb-3">
											<h5 class="card-header">{{ "Email address"|trans }}</h5>
											<div class="card-body">
												<p class="card-text">
													{{ form_row(form.email) }}
												</p>
											</div>
										</div>
										<div class="card">
											<h5 class="card-header">{{ "Change Password"|trans }}</h5>
											<div class="card-body">
												<p class="card-text">
													{{ form_row(form.password0) }}
													{{ form_row(form.password1) }}
													{{ form_row(form.password2) }}
												</p>
											</div>
										</div>
									</div>
								</div>
								<p></p>
								<button class="btn btn-success" type="submit">{{ "Update profile"|trans }}</button>
								{{ form_end(form) }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base/page.html.twig' %}

{% block body %}
<div class="card">
	<div class="card-header">
		<h3 class="card-title">{{ "Users"|trans }}</h3>
	</div>
	<div class="table-responsive">
		<table class="table card-table table-vcenter text-nowrap datatable">
			<thead>
				<tr>
					{# <th class="w-1"><input class="form-check-input m-0 align-middle" type="checkbox" aria-label="Select all invoices"></th> #}
					<th class="w-1">{{ "Id"|trans }}</th>
					<th>{{ "Name"|trans }}</th>
					<th class="d-none d-lg-table-cell">{{ "Domains"|trans }}</th>
					<th class="d-none d-lg-table-cell">{{ "Verified"|trans }}</th>
					<th>{{ "Type"|trans }}</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
{% for user in users %}
				<tr>
					<td><span class="text-secondary">{{ user.id }}</span></td>
					<td>{{ user.firstname }} {{ user.lastname }}</td>
					<td class="d-none d-lg-table-cell">
						{% for domain in user.domains %}
							{% if loop.index == 0 and user.domains|length > 0 %},{% endif %}
								<span class="text-secondary">{{ domain.fqdn }}</span>
							{% if loop.index != loop.length %},{% endif %}
						{% endfor %}
					</td>
					<td class="d-none d-lg-table-cell">
						{% if user.verified %}
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-square-check text-green"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M18.333 2c1.96 0 3.56 1.537 3.662 3.472l.005 .195v12.666c0 1.96 -1.537 3.56 -3.472 3.662l-.195 .005h-12.666a3.667 3.667 0 0 1 -3.662 -3.472l-.005 -.195v-12.666c0 -1.96 1.537 -3.56 3.472 -3.662l.195 -.005h12.666zm-2.626 7.293a1 1 0 0 0 -1.414 0l-3.293 3.292l-1.293 -1.292l-.094 -.083a1 1 0 0 0 -1.32 1.497l2 2l.094 .083a1 1 0 0 0 1.32 -.083l4 -4l.083 -.094a1 1 0 0 0 -.083 -1.32z" /></svg>
						{% else %}
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="icon icon-tabler icons-tabler-filled icon-tabler-square-x text-red"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19 2h-14a3 3 0 0 0 -3 3v14a3 3 0 0 0 3 3h14a3 3 0 0 0 3 -3v-14a3 3 0 0 0 -3 -3zm-9.387 6.21l.094 .083l2.293 2.292l2.293 -2.292a1 1 0 0 1 1.497 1.32l-.083 .094l-2.292 2.293l2.292 2.293a1 1 0 0 1 -1.32 1.497l-.094 -.083l-2.293 -2.292l-2.293 2.292a1 1 0 0 1 -1.497 -1.32l.083 -.094l2.292 -2.293l-2.292 -2.293a1 1 0 0 1 1.32 -1.497z" /></svg>
						{% endif %}
					</td>
					<td>
						{% for role in user.roles %}
							{% if role == "ROLE_ADMIN" %}
								<span class="text-red">Admin</span>
							{% elseif role == "ROLE_USER" %}
								<span class="text-secondary">User</span>
							{% endif %}
							{% if loop.index != loop.length %},{% endif %}
						{% endfor %}
					</td>
					<td class="text-end">
						<span class="dropdown">
							<button class="btn dropdown-toggle align-text-top"{# data-bs-boundary="viewport"#} data-bs-toggle="dropdown">{{ "Actions"|trans }}</button>
							<div class="dropdown-menu dropdown-menu dropdown-menu-end">
								<a class="dropdown-item" href="{{ path('app_users_edit', {user: user.id}) }}">{{ "Edit"|trans }}</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item " href="{{ path('app_users_delete', {user: user.id}) }}"><span class="text-red">{{ "Delete"|trans }}</span></a>
							</div>
						</span>
					</td>
				</tr>
{% endfor %}
			</tbody>
		</table>
	</div>
	{% include 'base/pagination.html.twig' with { basepath: path('app_users')} %}
</div>
{% endblock %}